// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: xai/api/v1/sample.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Sample_SampleText_FullMethodName          = "/xai_api.Sample/SampleText"
	Sample_SampleTextStreaming_FullMethodName = "/xai_api.Sample/SampleTextStreaming"
)

// SampleClient is the client API for Sample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// An API service for sampling the responses of available language models.
type SampleClient interface {
	// Get raw sampling of text response from the model inference.
	SampleText(ctx context.Context, in *SampleTextRequest, opts ...grpc.CallOption) (*SampleTextResponse, error)
	// Get streaming raw sampling of text response from the model inference.
	SampleTextStreaming(ctx context.Context, in *SampleTextRequest, opts ...grpc.CallOption) (Sample_SampleTextStreamingClient, error)
}

type sampleClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleClient(cc grpc.ClientConnInterface) SampleClient {
	return &sampleClient{cc}
}

func (c *sampleClient) SampleText(ctx context.Context, in *SampleTextRequest, opts ...grpc.CallOption) (*SampleTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SampleTextResponse)
	err := c.cc.Invoke(ctx, Sample_SampleText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleClient) SampleTextStreaming(ctx context.Context, in *SampleTextRequest, opts ...grpc.CallOption) (Sample_SampleTextStreamingClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sample_ServiceDesc.Streams[0], Sample_SampleTextStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &sampleSampleTextStreamingClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Sample_SampleTextStreamingClient interface {
	Recv() (*SampleTextResponse, error)
	grpc.ClientStream
}

type sampleSampleTextStreamingClient struct {
	grpc.ClientStream
}

func (x *sampleSampleTextStreamingClient) Recv() (*SampleTextResponse, error) {
	m := new(SampleTextResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SampleServer is the server API for Sample service.
// All implementations must embed UnimplementedSampleServer
// for forward compatibility
//
// An API service for sampling the responses of available language models.
type SampleServer interface {
	// Get raw sampling of text response from the model inference.
	SampleText(context.Context, *SampleTextRequest) (*SampleTextResponse, error)
	// Get streaming raw sampling of text response from the model inference.
	SampleTextStreaming(*SampleTextRequest, Sample_SampleTextStreamingServer) error
	mustEmbedUnimplementedSampleServer()
}

// UnimplementedSampleServer must be embedded to have forward compatible implementations.
type UnimplementedSampleServer struct {
}

func (UnimplementedSampleServer) SampleText(context.Context, *SampleTextRequest) (*SampleTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SampleText not implemented")
}
func (UnimplementedSampleServer) SampleTextStreaming(*SampleTextRequest, Sample_SampleTextStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SampleTextStreaming not implemented")
}
func (UnimplementedSampleServer) mustEmbedUnimplementedSampleServer() {}

// UnsafeSampleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleServer will
// result in compilation errors.
type UnsafeSampleServer interface {
	mustEmbedUnimplementedSampleServer()
}

func RegisterSampleServer(s grpc.ServiceRegistrar, srv SampleServer) {
	s.RegisterService(&Sample_ServiceDesc, srv)
}

func _Sample_SampleText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServer).SampleText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sample_SampleText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServer).SampleText(ctx, req.(*SampleTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sample_SampleTextStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SampleTextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SampleServer).SampleTextStreaming(m, &sampleSampleTextStreamingServer{ServerStream: stream})
}

type Sample_SampleTextStreamingServer interface {
	Send(*SampleTextResponse) error
	grpc.ServerStream
}

type sampleSampleTextStreamingServer struct {
	grpc.ServerStream
}

func (x *sampleSampleTextStreamingServer) Send(m *SampleTextResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Sample_ServiceDesc is the grpc.ServiceDesc for Sample service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sample_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xai_api.Sample",
	HandlerType: (*SampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SampleText",
			Handler:    _Sample_SampleText_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SampleTextStreaming",
			Handler:       _Sample_SampleTextStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xai/api/v1/sample.proto",
}
