// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: xai/api/v1/video.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Video_GenerateVideo_FullMethodName    = "/xai_api.Video/GenerateVideo"
	Video_GetDeferredVideo_FullMethodName = "/xai_api.Video/GetDeferredVideo"
)

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// An API service for interaction with video generation models.
type VideoClient interface {
	// Create a video based on a text prompt and optionally an image.
	// If an image is provided, generates video with the image as the first frame (image-to-video).
	// If no image is provided, generates video from text only (text-to-video).
	//
	// This is an asynchronous operation. The method returns immediately with a request_id
	// that can be used to poll for the result using GetDeferredVideo.
	GenerateVideo(ctx context.Context, in *GenerateVideoRequest, opts ...grpc.CallOption) (*StartDeferredResponse, error)
	// Gets the result of a video generation started by calling `GenerateVideo`.
	GetDeferredVideo(ctx context.Context, in *GetDeferredVideoRequest, opts ...grpc.CallOption) (*GetDeferredVideoResponse, error)
}

type videoClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoClient(cc grpc.ClientConnInterface) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) GenerateVideo(ctx context.Context, in *GenerateVideoRequest, opts ...grpc.CallOption) (*StartDeferredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDeferredResponse)
	err := c.cc.Invoke(ctx, Video_GenerateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetDeferredVideo(ctx context.Context, in *GetDeferredVideoRequest, opts ...grpc.CallOption) (*GetDeferredVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeferredVideoResponse)
	err := c.cc.Invoke(ctx, Video_GetDeferredVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
// All implementations must embed UnimplementedVideoServer
// for forward compatibility
//
// An API service for interaction with video generation models.
type VideoServer interface {
	// Create a video based on a text prompt and optionally an image.
	// If an image is provided, generates video with the image as the first frame (image-to-video).
	// If no image is provided, generates video from text only (text-to-video).
	//
	// This is an asynchronous operation. The method returns immediately with a request_id
	// that can be used to poll for the result using GetDeferredVideo.
	GenerateVideo(context.Context, *GenerateVideoRequest) (*StartDeferredResponse, error)
	// Gets the result of a video generation started by calling `GenerateVideo`.
	GetDeferredVideo(context.Context, *GetDeferredVideoRequest) (*GetDeferredVideoResponse, error)
	mustEmbedUnimplementedVideoServer()
}

// UnimplementedVideoServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServer struct {
}

func (UnimplementedVideoServer) GenerateVideo(context.Context, *GenerateVideoRequest) (*StartDeferredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateVideo not implemented")
}
func (UnimplementedVideoServer) GetDeferredVideo(context.Context, *GetDeferredVideoRequest) (*GetDeferredVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeferredVideo not implemented")
}
func (UnimplementedVideoServer) mustEmbedUnimplementedVideoServer() {}

// UnsafeVideoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServer will
// result in compilation errors.
type UnsafeVideoServer interface {
	mustEmbedUnimplementedVideoServer()
}

func RegisterVideoServer(s grpc.ServiceRegistrar, srv VideoServer) {
	s.RegisterService(&Video_ServiceDesc, srv)
}

func _Video_GenerateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GenerateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GenerateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GenerateVideo(ctx, req.(*GenerateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetDeferredVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeferredVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetDeferredVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetDeferredVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetDeferredVideo(ctx, req.(*GetDeferredVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Video_ServiceDesc is the grpc.ServiceDesc for Video service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Video_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xai_api.Video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateVideo",
			Handler:    _Video_GenerateVideo_Handler,
		},
		{
			MethodName: "GetDeferredVideo",
			Handler:    _Video_GetDeferredVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xai/api/v1/video.proto",
}
